# Required secrets
#   UNITY_LICENSE: The contents of Unity license file
name: 🎮 Build Demo Player

env:
  unityVersion: 2022.3.10f1
  targetPlatform: WebGL

on:
  workflow_call:
    inputs:
      repository:
        description: The repository to run the workflow on
        required: true
        type: string
      ref:
        description: The branch or tag to checkout
        required: true
        type: string
    secrets:
      UNITY_LICENSE:
        description: The contents of Unity license file
        required: true
  workflow_dispatch:
    inputs:
      repository:
        description: The repository to run the workflow on
        required: true
        type: string
      ref:
        description: The branch or tag to checkout
        required: true
        type: string

jobs:
  build:
    name: 🎮 Build Demo Player
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: 📥 Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ inputs.repository }}-${{ inputs.ref }}-${{ env.unityVersion }}-${{ env.targetPlatform }}-${{ github.sha }}
          restore-keys: |
            Library-${{ inputs.repository }}-${{ inputs.ref }}-${{ env.unityVersion }}-${{ env.targetPlatform }}-
            Library-${{ inputs.repository }}-${{ inputs.ref }}-${{ env.unityVersion }}-
            Library-${{ inputs.repository }}-${{ inputs.ref }}-
            Library-${{ inputs.repository }}-
            Library-

      - name: 🛠️ Build Demo Player
        uses: game-ci/unity-builder@v3
        timeout-minutes: 30
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ env.unityVersion }}
          targetPlatform: WebGL
          allowDirtyBuild: true

      - name: 📦 Upload Demo Player
        uses: actions/upload-artifact@v3
        with:
          name: Demo
          path: build/WebGL/WebGL