name: run_from_delete_issue

on:
  workflow_dispatch:
    inputs:
      versions:
        description: "Unity versions array to build"
        required: true
        default: '[ \"2018.4.30f1\" ]'
      modules:
        description: "Unity modules array to build.\n(base|linux-il2cpp|windows-mono|mac-mono|ios|android|webgl)"
        required: true
        default: '[ \"base\", \"linux-il2cpp\", \"windows-mono\", \"mac-mono\", \"ios\", \"android\", \"webgl\" ]'
  issues:
    types: [opened, edited, deleted]

jobs:
  setup:
    if: github.event_name != 'issues' || github.event.issue.body == '/build-editor'
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.setup.outputs.versions }}
      modules: ${{ steps.setup.outputs.modules }}
    steps:
      - id: setup
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            echo 'versions=[ "${{ github.event.issue.title }}" ]' | tee >> $GITHUB_OUTPUT
            echo 'modules=[ "base", "linux-il2cpp", "windows-mono", "mac-mono", "ios", "android", "webgl" ]' | tee >> $GITHUB_OUTPUT
          else
            echo "versions=${{ github.event.inputs.versions }}" | tee >> $GITHUB_OUTPUT
            echo "modules=${{ github.event.inputs.modules }}" | tee >> $GITHUB_OUTPUT
          fi

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.setup.outputs.versions) }}
        module: ${{ fromJson(needs.setup.outputs.modules) }}
    steps:

      - uses: actions/checkout@v3

      - run: cat .env | sed 's/=\" *$/<<EOD/g' | sed 's/^\"/EOD/g' | grep '^[^# ]' >> $GITHUB_ENV

      - run: |
          echo "======== Target tag ========"
          echo "${{ matrix.version }}-${{ matrix.module }}"

          echo "======== Excluded image tags ========"
          echo -n "${{ env.EXCLUDE_IMAGE_TAGS }}" | grep '.' | tee .excludedTags

          [ -n "$(echo ${{ matrix.version }}-${{ matrix.module }} | grep -f .excludedTags)" ] && echo "skip=true" | tee >> $GITHUB_ENV

      - if: env.skip != 'true'
        run: |
          echo "Building ${{ matrix.version }} for ${{ matrix.module }}"
