name: run_from_issue

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "dryRun: Skip the image build and push."
        required: true
        default: "false"
  issue_comment:
    types: [created]

jobs:
  setup:
    if: github.event_name != 'issue_comment' ||
        startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    env:
      dryRun: ${{ github.event.inputs.dryRun }}
    steps:
      - run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.comment.body: ${{ github.event.comment.body }}"
          echo "dryRun: ${dryRun}, ${{ github.event.inputs.dryRun }}"
