name: 📷 Snapshot

on:
  workflow_dispatch:
    inputs:
      from:
        required: true
      to:
        required: true
      path:
        required: true
  workflow_call:
    inputs:
      from:
        required: true
        type: string
      to:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  merge:
    name: 📷 Snapshot
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.from }}
          path: from

      - name: 🚚 Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.to }}
          path: to

      - working-directory: to
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git rm -rf --ignore-unmatch .
          cp -r 'from/${{ inputs.path }}/*' ./

          git commit -am "📷 Snapshot '${{ inputs.path }}' from '${{ inputs.from }}' to '${{ inputs.to }}'"
          git push origin ${{ inputs.to }}