name: "Transfer"

on:
  workflow_dispatch:
    inputs:
      unityVersions:
        description: "Unity versions array to build"
        required: true
        default: '[ "2018.4.30f1" ]'
      module:
        description: "Unity modules array to build.\n(-base|-linux-il2cpp|-windows-mono|-mac-mono|-ios|-android|-webgl)"
        required: true
        default: "-base"
      version:
        description: "Image version (e.g. -1.3.0)"
        required: true
        default: "-1.3.0"

env:
  unityImageTo: ghcr.io/mob-sakai/unity3d
  unityImageFrom: docker.io/mobsakai/unity3d

jobs:
  build:
    name: Transfer ${{ matrix.unityVersions }}${{ inputs.module }}${{ inputs.version }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: write
    env:
      tag: ${{ matrix.unityVersions }}${{ inputs.module }}${{ inputs.version }}
      tagWithoutVersion: ${{ matrix.unityVersions }}${{ inputs.module }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        unityVersions: ${{ fromJson(inputs.unityVersions) }}
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mob-sakai
          password: ${{ github.token }}

      - name: Pull ${{ env.unityImageFrom }}:${{ env.tag }}
        run: |
          docker pull ${{ env.unityImageFrom }}:${{ env.tag }}

      - name: Transfer to ${{ env.unityImageTo }}:${{ env.tag }}
        run: |
          docker tag ${{ env.unityImageFrom }}:${{ env.tag }} ${{ env.unityImageTo }}:${{ env.tag }}
          docker push ${{ env.unityImageTo }}:${{ env.tag }}

      - name: Transfer to ${{ env.unityImageTo }}:${{ env.tagWithoutVersion }}
        id: tr
        if: inputs.version != ''
        run: |
          docker tag ${{ env.unityImageFrom }}:${{ env.tag }} ${{ env.unityImageTo }}:${{ env.tagWithoutVersion }}
          docker push ${{ env.unityImageTo }}:${{ env.tagWithoutVersion }}
          echo "versionWithV=`echo ${{ inputs.version }} | sed 's/-/-v/' | sed 's/vv/v/'`" | tee $GITHUB_OUTPUT

      - name: Transfer to ${{ env.unityImageTo }}:${{ env.tagWithoutVersion }}${{ steps.tr.outputs.versionWithV }}
        if: inputs.version != '' && inputs.version != steps.tr.outputs.versionWithV
        run: |
          docker tag ${{ env.unityImageFrom }}:${{ env.tag }} ${{ env.unityImageTo }}:${{ env.tagWithoutVersion }}${{ steps.tr.outputs.versionWithV }}
          docker push ${{ env.unityImageTo }}:${{ env.tagWithoutVersion }}${{ steps.tr.outputs.versionWithV }}

      - name: Transfer to ${{ env.unityImageTo }}:${{ matrix.unityVersions }}
        if: inputs.module == '-base'
        run: |
          echo "Transfer ${{ env.unityImageFrom }}:${{ env.tag }} -> ${{ env.unityImageTo }}:${{ matrix.unityVersions }}"
          docker tag ${{ env.unityImageFrom }}:${{ env.tag }} ${{ env.unityImageTo }}:${{ matrix.unityVersions }}
          docker push ${{ env.unityImageTo }}:${{ matrix.unityVersions }}
